const ELEMENT_COLORS = {
  nature: "#84cc16",
  fire: "#f97316",
  ice: "#60a5fa",
  astral: "#c084fc",
  darkness: "#a78bfa",
  holy: "#facc15",
};

const RARITY_PROGRESSION = {
  common: { minAttackCd: 0.32, xpBase: 38, xpGrowth: 1.4, damageMul: 1.28 },
  uncommon: { minAttackCd: 0.3, xpBase: 42, xpGrowth: 1.44, damageMul: 1.3 },
  rare: { minAttackCd: 0.28, xpBase: 48, xpGrowth: 1.47, damageMul: 1.32 },
  unique: { minAttackCd: 0.26, xpBase: 54, xpGrowth: 1.5, damageMul: 1.34 },
};

const FALLBACK_BLUEPRINTS = {
  sentinel: {
    label: "Sentinel",
    cost: 120,
    range: 255,
    damage: 56,
    attackCd: 0.62,
    damageType: "piercing",
    color: "#1e40af",
    minAttackCd: 0.32,
    xpBase: 38,
    xpGrowth: 1.4,
    specialText: "piercing",
    maxLevelMultiShot: 2,
    upgrade: {
      damageMul: 1.29,
      damageFlat: 6,
      rangeFlat: 11,
      attackCdMul: 0.95,
    },
  },
  pyro: {
    label: "Pyro",
    cost: 200,
    range: 100,
    damage: 6,
    attackCd: 0.1,
    damageType: "magic",
    color: "#f97316",
    minAttackCd: 0.1,
    xpBase: 42,
    xpGrowth: 1.45,
    specialText: "zone(4), burn(1), magic, ground",
    bonusSpecialText: "zone(10), burn(1), magic, ground",
    hitsAllInRange: true,
    maxTargetsPerShot: 4,
    bonusMaxTargetsPerShot: 10,
    burnOnHit: 1,
    targetGroundOnly: true,
    upgrade: {
      damageMul: 1.32,
      damageFlat: 2,
      rangeFlat: 4,
      attackCdMul: 0.985,
    },
  },
  arc: {
    label: "Elfe",
    cost: 180,
    range: 290,
    damage: 72,
    attackCd: 1.0,
    damageType: "piercing",
    color: "#86efac",
    minAttackCd: 0.42,
    xpBase: 48,
    xpGrowth: 1.47,
    specialText: "piercing, eyes",
    hasEyes: true,
    bonusDamageType: "chaos",
    bonusSpecialText: "chaos, eyes",
    upgrade: {
      damageMul: 1.34,
      damageFlat: 8,
      rangeFlat: 12,
      attackCdMul: 0.96,
    },
  },
  frozen: {
    label: "Frozen",
    cost: 200,
    range: 120,
    damage: 10,
    attackCd: 2.0,
    damageType: "magic",
    color: "#7dd3fc",
    minAttackCd: 0.8,
    xpBase: 48,
    xpGrowth: 1.48,
    specialText: "slow(5), splash(30), magic",
    bonusSpecialText: "freeze(1), slow(5), splash(30), magic",
    splashRadius: 30,
    freezeDuration: 0,
    bonusFreezeDuration: 1,
    iceSlowDuration: 5,
    iceSlowMul: 0.5,
    burnReductionOnFreezeHit: 10,
    burnReductionOnFreezeSplash: 5,
    upgrade: {
      damageMul: 1.2,
      damageFlat: 3,
      rangeFlat: 6,
      attackCdMul: 0.97,
    },
  },
  ronce: {
    label: "Ronce",
    cost: 180,
    range: 80,
    damage: 30,
    attackCd: 1.0,
    damageType: "piercing",
    color: "#166534",
    minAttackCd: 0.35,
    xpBase: 44,
    xpGrowth: 1.46,
    specialText: "slowPoison(20), poison(1), piercing",
    poisonOnHit: 1,
    poisonSlowDuration: 20,
    poisonSlowMul: 0.75,
    maxLevelMultiShot: 3,
    upgrade: {
      damageMul: 1.28,
      damageFlat: 5,
      rangeFlat: 5,
      attackCdMul: 0.96,
    },
  },
  cannon: {
    label: "Canon",
    cost: 190,
    range: 160,
    damage: 100,
    attackCd: 0.75,
    damageType: "bludgeoning",
    color: "#8b5a2b",
    minAttackCd: 0.35,
    xpBase: 46,
    xpGrowth: 1.46,
    specialText: "splash(30), ground, bludgeoning",
    splashRadius: 30,
    splashDamageRatio: 0.35,
    targetGroundOnly: true,
    maxLevelStunChance: 0.1,
    stunDuration: 1,
    upgrade: {
      damageMul: 1.3,
      damageFlat: 8,
      rangeFlat: 7,
      attackCdMul: 0.96,
    },
  },
  ricochet: {
    label: "Ricochet",
    cost: 500,
    range: 200,
    damage: 100,
    attackCd: 1.0,
    damageType: "bludgeoning",
    color: "#ec4899",
    minAttackCd: 0.3,
    xpBase: 54,
    xpGrowth: 1.5,
    specialText: "bounce(1), bludgeoning",
    ricochetByLevel: true,
    ricochetRadius: 50,
    ricochetDamageRatio: 0.5,
    ricochetMaxLevelBonus: 5,
    upgrade: {
      damageMul: 1.31,
      damageFlat: 10,
      rangeFlat: 8,
      attackCdMul: 0.96,
    },
  },
  machinegun: {
    label: "Machinegun",
    cost: 600,
    range: 266,
    damage: 33,
    attackCd: 0.075,
    damageType: "chaos",
    color: "#6b7280",
    minAttackCd: 0.075,
    xpBase: 58,
    xpGrowth: 1.52,
    specialText: "chaos",
    maxLevelMultiShot: 2,
    upgrade: {
      damageMul: 1.22,
      damageFlat: 4,
      rangeFlat: 7,
      attackCdMul: 0.985,
    },
  },
  scorpio: {
    label: "Scorpio",
    cost: 190,
    range: 270,
    damage: 50,
    attackCd: 0.5,
    damageType: "laser",
    color: "#c0c0c0",
    minAttackCd: 0.18,
    xpBase: 44,
    xpGrowth: 1.46,
    specialText: "air, laser, multiShot(2)",
    bonusSpecialText: "air, laser, eyes, multiShot(5)",
    maxLevelMultiShot: 5,
    targetAirOnly: true,
    hasEyes: false,
    upgrade: {
      damageMul: 1.28,
      damageFlat: 6,
      rangeFlat: 8,
      attackCdMul: 0.965,
    },
  },
  aura: {
    label: "Aura",
    cost: 50,
    range: 70,
    damage: 0,
    attackCd: 1,
    damageType: "support",
    color: "#fef08a",
    minAttackCd: 1,
    xpBase: 40,
    xpGrowth: 1.42,
    specialText: "effet(power), inactif",
    startLevel: 0,
    itemSlots: 1,
    isAuraTower: true,
    footprintWidth: 2,
    footprintHeight: 2,
    initialAuraEffect: "power",
    upgrade: {
      damageMul: 1,
      damageFlat: 0,
      rangeFlat: 0,
      attackCdMul: 1,
    },
  },
};

function toNumber(value, fallback = 0) {
  return Number.isFinite(value) ? value : fallback;
}

function makeBlueprintFromDocTower(entry, fallbackId) {
  const min = toNumber(entry.dmg_min, 1);
  const max = toNumber(entry.dmg_max, min);
  const avgDamage = Math.max(1, Math.floor((min + max) / 2));
  const rarityKey = String(entry.rarity ?? "common").toLowerCase();
  const rarity = RARITY_PROGRESSION[rarityKey] ?? RARITY_PROGRESSION.common;
  const elementKey = String(entry.element ?? "astral").toLowerCase();

  return {
    label: String(entry.name_english ?? `Tower ${entry.id}`),
    cost: Math.max(40, Math.floor(toNumber(entry.cost, 120))),
    range: Math.max(120, Math.floor(toNumber(entry.attack_range, 240))),
    damage: avgDamage,
    attackCd: Math.max(0.35, toNumber(entry.attack_cd, 0.8)),
    damageType: String(entry.attack_type ?? "physical").toLowerCase() === "physical"
      ? "physical"
      : "elemental",
    color: ELEMENT_COLORS[elementKey] ?? "#93c5fd",
    minAttackCd: rarity.minAttackCd,
    xpBase: rarity.xpBase,
    xpGrowth: rarity.xpGrowth,
    upgrade: {
      damageMul: rarity.damageMul,
      damageFlat: 6,
      rangeFlat: 10,
      attackCdMul: 0.955,
    },
    _source: "doc",
    _sourceId: entry.id,
    _id: fallbackId,
  };
}

export function createTowerBlueprints(registry) {
  void registry;
  return {
    blueprints: FALLBACK_BLUEPRINTS,
    order: Object.keys(FALLBACK_BLUEPRINTS),
    source: "fallback",
  };
}
